version: "3.9"

services:
  wordpress:
    image: wordpress:5.8.1-php8.0-apache
    user: "${UID}:${UID}"
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_FS_METHOD: "direct"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_LOCAL_PORT}:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_LOCAL_NAME}"
      MYSQL_USER: "${DB_LOCAL_USER}"
      MYSQL_PASSWORD: "${DB_LOCAL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_LOCAL_ROOT_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 10000:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_PMADB: "${DB_NAME}"

volumes:
  db_data:
