version: "3.9"

services:
  wordpress:
    container_name: wordpress_sandbox_wordpress
    image: wordpress:5.8.1-php8.0-apache
    user: "${UID}:${UID}"
    volumes:
      - type: bind
        source: ./public_html
        target: /var/www/html
    ports:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_FS_METHOD: "direct"
    networks:
      - proxy_traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress_sandbox_wordpress.rule=Host(`sparky.devlocal`)"
      - "traefik.http.services.wordpress_sandbox_wordpress.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress_sandbox_wordpress.entrypoints=web"
      - "traefik.docker.network=proxy_traefik"

  db:
    container_name: wordpress_sandbox_db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_LOCAL_PORT}:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_LOCAL_NAME}"
      MYSQL_USER: "${DB_LOCAL_USER}"
      MYSQL_PASSWORD: "${DB_LOCAL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_LOCAL_ROOT_PASSWORD}"
    networks:
      - default
      - proxy_traefik

networks:
  proxy_traefik:
    name: proxy_traefik
    external: true
  app:
    driver: bridge

volumes:
  db_data:
